### ISSUE TITLE
Russian roulette 

### ISSUE THREAD

**Issue by ther3y3s** [Yazaar/Streamlabs-Chatbot-Scripts#3]
First of all, thanks for this script, i love it! Really thanks for your job, I really appreciated it!
I noticed when someone wrote in chat !rr, so miss command because incomplete, if they try to wrote after in good way the can't because need to wait cooldown. Is there a possibility to fix this?

**Comment by Yazaar** [comment]
Ah, noticed this now sorry, it should now be solved if still interested 👍
If you end up using it, let me know if I broke anything else 🤣
[direct download link](https://github.com/Yazaar/Streamlabs-Chatbot-Scripts/raw/RussianRoulette/RussianRoulette.zip)
